server:
  port: 18888
spring:
  datasource:
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/managestage?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static/,classpath:/static/pdf/,classpath:/static/pdf/result
#  security:
#    user:
#      name: user
#      password: 111111

#允许循环依赖
spring.main.allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Redis 配置
spring.redis.host: localhost
spring.redis.port: 6379

wpca:
  jwt:
    header: Authorization
    expire: 604800 #7天
    secret: xrjert123jkhi80134ghjk3ghjkfk543  # 密钥


logging:
  level:
    root: info

